[bell]
animation = "EaseOut"
color = "#666666"
duration = 200

[font]
size = 11.0

[font.normal]
family = "Monaspace Neon"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"
