" PolyFloyd's .vimrc

version 7.0

" Vundle Settings
set nocompatible " be iMproved, required
filetype off     " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim' " let Vundle manage Vundle, required
Plugin 'airblade/vim-gitgutter'
Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-airline'
Plugin 'exu/pgsql.vim'
Plugin 'fatih/vim-go'
Plugin 'godlygeek/tabular'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'jlanzarotta/bufexplorer'
Plugin 'kien/ctrlp.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'sirtaj/vim-openscad'
Plugin 'tikhomirov/vim-glsl'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'vim-scripts/nginx.vim'

call vundle#end()         " required
filetype plugin indent on " required

" VIM Settings
set autoindent
set backspace=2
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,default,latin1
set fillchars=vert:│,fold:\ 
set foldmethod=marker
set grepprg=grep\ -nH\ $*
set hidden
set history=50
set hlsearch
set incsearch
set laststatus=2
set linebreak
set list
set listchars=tab:│\ ,trail:⋯,precedes:←,extends:→
set mouse=a
set mousemodel=extend
set nofoldenable
set nomodeline
set nostartofline
set nrformats=alpha
set path+=src
set shiftwidth=4
set shortmess=flmnxoOtTI
set showcmd
set showtabline=2
set smartindent
set smarttab
set splitright
set suffixes=.bak,~,.o,.h,.info,.swp,.obj,.aux,.log,.dvi,.bbl,.out,.o,.lo,.d,.class,.pyc
set switchbuf=useopen
set tabstop=4
set termencoding=utf-8
set viminfo='20,\"500,%
set virtualedit=block
set wildignore+=*/*.bak,*/*~,*/*.o,*/*.sw*,*/*.sw*.obj,*/*.aux,*/*.dvi,*/*.bbl,*/*.out,*/*.o,*/*.lo,*/*.d,*/*.class,*/*.pyc
set wildmenu
set window=61
syntax on

" Key Mappings
nmap ; :
map <C-t>     :tabnew<CR>
map <C-q>     :tabclose<CR>
map <C-S-tab> :tabprevious<CR>
map <C-tab>   :tabnext<CR>
map <F10>     :NERDTreeToggle<CR>
if has("gui_running")
	inoremap <C-Space> <C-x><C-o>
elseif has("unix")
	inoremap <Nul> <C-x><C-o>
endif

" Colors & Theming
hi Normal      ctermfg=252 ctermbg=232
hi LineNr      ctermbg=0 ctermfg=12
hi NonText     ctermbg=0 ctermfg=12
hi ColorColumn ctermbg=0
hi Search      term=reverse ctermbg=8
hi Visual      term=reverse ctermbg=8
hi Comment     term=bold ctermfg=8 ctermbg=none
colorscheme solarized
set background=dark
set guifont=Terminus\ 12
set guioptions-=m " Remove menubar
set guioptions-=T " Remove toolbar
set guioptions-=L " Remove left scrollbar
set guioptions-=r " Remove right scrollbar
let &colorcolumn="80"
let g:NERDTreeDirArrows=1
let g:NERDTreeMinimalUI=1
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_powerline_fonts=0
let g:airline_theme='solarized'
let g:airline#extensions#whitespace#checks = [ 'trailing' ]

" Autocmds
autocmd BufRead,BufNewFile *.md              setlocal ft=markdown expandtab tabstop=2 shiftwidth=2
autocmd BufRead,BufNewFile *.c,*.h,*.cc,*.hh setlocal cin
autocmd BufRead,BufNewFile *.js,*.css,*.html,*.php set noexpandtab softtabstop=4 shiftwidth=4
autocmd BufRead,BufNewFile *.ino set ft=cpp noexpandtab tabstop=4 shiftwidth=4
autocmd BufRead,BufNewFile *.py set ft=python noexpandtab tabstop=4 shiftwidth=4
autocmd FileType css set omnifunc=csscomplete#CompleteCSS

" vim: set ft=vim
